[32mINFO    [0m courses.pytest_allure.pytest_practice.base_func.log_util:base.py:15 开始计算
[32mINFO    [0m courses.pytest_allure.pytest_practice.base_func.log_util:test_add_param.py:49 输入数据：文, 9.3, 期望结果是 TypeError
[32mINFO    [0m courses.pytest_allure.pytest_practice.base_func.log_util:base.py:18 结束计算
[32mINFO    [0m courses.pytest_allure.pytest_practice.base_func.log_util:base.py:12 结束测试